public enum CardEnum
{
    None = 0,
    ArcherTower = 1,
    MageTower = 2,
    ArtilleryTower = 3,
    Troop = 4,
    Bomb = 5,
    Lightning = 6,
    DarkHole = 7,
    RollToEnergy = 8,
    LightningPower = 9,
    TimeReverse = 10,
    TimeFreeze = 11,
    FreeBomb = 12,
    Add1Energy = 13,
    Add5Energy = 14,
    Add3Roll = 15,
    Add7Roll = 16,
    Napalm = 17,
}
