public enum CardEnum
{
    None = 0,
    ArcherTower = 1,
    MageTower = 2,
    ArtilleryTower = 3,
    Baracks = 4,
    Bomb = 5,
    BombRain = 6,
    AllTowerBuff = 7,
    ArcherTowerBuff = 8,
    ArtilleryTowerBuff = 9,
    IceAge = 10,
    TimeFreeze = 11,
    FreeBomb = 12,
    Add1Energy = 13,
    Add5Energy = 14,
    Add3Roll = 15,
    Add7Roll = 16,
}
